[en]
languageName = "English"
contentDir = "content/en"
weight = 10
[en.params]
languageISO = "EN"
languageTag = "en-US"
footer = 'Powered by :coffee: and Hugo, made by <a class=\"text-muted\" href=\"https://github.com/engeir\">@engeir</a>'
alertText = 'Chat with my telegram bot about northern lights! <a class=\"alert-link stretched-link\" href=\"https://t.me/NorthernLightsForecastBot\">Visit @NorthernLightsForecastBot</a>'

[nb]
languageName = "Norsk"
contentDir = "content/nb"
weight = 15
[nb.params]
languageISO = "NB"
languageTag = "nb-NB"
footer = 'Drevet av :coffee: og <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, laget av <a class=\"text-muted\" href=\"https://github.com/engeir\">@engeir</a>'
alertText = 'Chat med min telegram bot om nordlys! <a class=\"alert-link stretched-link\" href=\"https://t.me/NorthernLightsForecastBot\">Besøk @NorthernLightsForecastBot</a>'
