[en]
contentDir = "content/en"
languageName = "English"
weight = 10
[en.params]
alertText = 'Chat with my telegram bot about northern lights! <a class=\"alert-link stretched-link\" href="https://t.me/NorthernLightsForecastBot">Visit @NorthernLightsForecastBot</a>'
footer = 'Powered by :coffee: and <a class=\"text-muted\" href="https://gohugo.io/">Hugo</a>, made by <a class=\"text-muted\" href="https://github.com/engeir">@engeir</a>'
languageISO = "EN"
languageTag = "en-GB"

[nb]
contentDir = "content/nb"
languageName = "Norsk"
weight = 15
[nb.params]
alertText = 'Chat med min telegram bot om nordlys! <a class=\"alert-link stretched-link\" href="https://t.me/NorthernLightsForecastBot">Besøk @NorthernLightsForecastBot</a>'
footer = 'Drevet av :coffee: og <a class=\"text-muted\" href="https://gohugo.io/">Hugo</a>, laget av <a class=\"text-muted\" href="https://github.com/engeir">@engeir</a>'
languageISO = "NB"
languageTag = "nb-NB"
