# Meta Data for SEO

## Homepage
title = "eirikre"
# titleSeparator = "-"
# titleAddition = ""
description = "This is a website filled up with projects I have done and anything else I find interesting."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_GB"
domainTLD = "doks.netlify.app"
titleHome = "Doks Theme"

## Twitter Cards
# twitterSite = "@E"
twitterCreator = "@EngerEirik"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Doks"
schemaAuthor = "Henk Verlinde"
schemaAuthorTwitter = "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/h-enk"
schemaLocale = "en-GB"
schemaLogo = "my-github-logo.jpg"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "my-github-logo.jpg"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/getdoks"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/h-enk/doks"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by :coffee: and <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, made by <a class=\"text-muted\" href=\"https://github.com/engeir\">@engeir</a>"

# Feed
copyRight = "Copyright (c) 2022-2022 Eirik Enger"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Chat with my telegram bot about Northern Lights! <a class=\"alert-link stretched-link\" href=\"https://t.me/NorthernLightsForecastBot\">Visit @NorthernLightsForecastBot</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/engeir/flottflyt"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = true

# Search
# Saved by https://github.com/h-enk/doks/discussions/395
mainSections = ["blog", "posts"]

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = true
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
