[tools]
hk = "latest"
hugo = "latest"
node = "latest"
pinact = "latest"
pkl = "latest"
usage = "latest"
uv = "latest"
# "npm:sequoia-cli" = "latest"

[tasks.update]
description = "Update Doks"
run = "npm install @hyas/doks-core@latest"

[tasks.install]
description = "Install all packages"
run = "npm install"

[tasks.dev]
description = "Run the development server"
run = "npm run dev"

[tasks.clean]
description = "Run the development server"
run = "npm run clean:build"

[tasks.build]
description = "Build the static website"
outputs = ["public/**"]
run = "npm run build"
sources = [
  "package.json",
  "content/**",
  "assets/**",
  "layouts/**",
  "config/**",
] # skip running if these files haven't changed

[tasks.publish]
depends = ["build"]
description = "Publish the site to my server with rsync"
run = "rsync -rtvzP --delete ./public/ root@eirik.re:/var/www/flottflyt"
